# Generated by Django 5.1.3 on 2024-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
